title : Mark Costello

author :
  name : Mark Costello
  email : mark@markcostello.net
  github : http://github.com/mcos
  twitter : http://twitter.com/mjcos

markdown: rdiscount
pygments: true
permalink: pretty
